# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:13
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('bedroomNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('bathroomNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('insideFridge', models.BooleanField(default=False)),
                ('insideOven', models.BooleanField(default=False)),
                ('basement', models.BooleanField(default=False)),
                ('dateOfService', models.DateTimeField()),
                ('howOften', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('reviewText', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2017, 4, 26, 16, 13, 12, 899962, tzinfo=utc))),
            ],
        ),
    ]
