# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 16:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 26, 16, 13, 41, 6691, tzinfo=utc)),
        ),
    ]
