# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170426_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Yerevan', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 28, 10, 10, 54, 2872, tzinfo=utc)),
        ),
    ]
