# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170428_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='insideFridge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='insideOven',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='as@as.as', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.CharField(default='extras', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(default='bobby', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(default='boo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default=11111),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 4, 0, 1, 502767, tzinfo=utc)),
        ),
    ]
