# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170429_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='howOften',
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 29, 4, 34, 39, 72323, tzinfo=utc)),
        ),
    ]
