# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170429_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extras',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 30, 9, 18, 9, 948258, tzinfo=utc)),
        ),
    ]
