# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170430_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 30, 12, 41, 9, 943848, tzinfo=utc)),
        ),
    ]
